### PR TITLE
update scala versions

### PR DESCRIPTION
**Pull request by yanns**

### CODE REVIEW

**Comment by yanns** [comment]
https://github.com/scoverage/sbt-scoverage/issues/295

**Comment by avdv** [comment]
This problem has been resolved with sbt-scoverage 1.6.1, which uses scoverage 1.4.1 by default which in turn is (unfortunately) no longer compatible with Scala 2.13.0.

**Comment by avdv** [comment]
Also, it would be a good idea to employ the sbt-travis plugin, which sets the `scalaVersion` and `crossScalaVersions` from the `.travis.yml` file. No need to duplicate that.

**Comment by avdv** [comment]
Since I could not push onto this branch directly, I have created a new PR -> #90. Closing here.

**Pull request closed without merging**
