### PR TITLE
Support Scala 2.13

### PR DESCRIPTION
**Pull request by avdv**
Depends on PR #63

### CODE REVIEW

**Comment by analytically** [comment]
Scoverage plugin needs to be bumped to 1.4.0 for Travis to pass.

**Comment by avdv** [comment]
@yanns 	Any progress on this? (hope your vacation was good! :slightly_smiling_face:)

**Comment by lforite** [comment]
it seems that scoverage is not yet released for 2.13, hence the build failing

**Comment by avdv** [comment]
> it seems that scoverage is not yet released for 2.13, hence the build failing

That's what the other PR is for: #63 -- @yanns asked me to make separate PRs for every dependency update.

**Comment by yanns** [comment]
I merged https://github.com/leanovate/play-mockws/pull/63.
Can you please rebase on master?

**Comment by avdv** [comment]
> Can you please rebase on master?

sure thing!

**Comment by yanns** [comment]
I'll release that probably next week. Thx for your patience.

**Comment by yanns** [comment]
https://github.com/leanovate/play-mockws/releases/tag/v2.7.1

**Pull request merged**
