### PR TITLE
upgrade sbt to 0.13.13

### PR DESCRIPTION
**Pull request by agebhar1**
Upgrade sbt to new upstream release [0.13.13](https://github.com/sbt/sbt/releases/tag/v0.13.13).

### CODE REVIEW

**Comment by yanns** [comment]
Sorry, I've already committed the same change into master: https://github.com/leanovate/play-mockws/commit/f566ba3aef3a736b3c3f307f15c889b612e53604

;)

thx anyway!

**Comment by agebhar1** [comment]
:wink: ... @yanns can we expect a new release soon?

**Comment by yanns** [comment]
http://repo1.maven.org/maven2/de/leanovate/play-mockws/play-mockws_2.11/2.5.1/ ?
😉

**Comment by agebhar1** [comment]
awesome - thx!

**Pull request closed without merging**
