### PR TITLE
build: provide one module for each Play version

### PR DESCRIPTION
**Pull request by gaeljw**
Aims to resolve https://github.com/leanovate/play-mockws/issues/329

One sbt project is defined for each Play version but the code is not duplicated when possible thanks to the following structure of directories:
```
.
├── main
│   ├── play-2
│   ├── play-2-8
│   ├── play-2-9
│   └── scala
└── test
    ├── play-2
    ├── play-2-8
    ├── play-2-9
    └── scala
```

I've initiated a `play-2` folder in prevision of merging [Play 3.0 support](https://github.com/leanovate/play-mockws/pull/322) which will require creating a `play-3` folder for Akka vs. Pekko stuff.

---

Note that I chose not to use sbt-project-matrix after having tried it because it felt too complex to manage additional axes for no strong benefit IMHO.

---

A side effect of this change is that we cannot use anymore sbt-github-actions because of [this](https://github.com/sbt/sbt-github-actions#generative-1): 
> (...) A corollary of this is that it is not possible (yet) to have specific subprojects which build with different Scala versions, Java versions, or OSes. This is theoretically possible but it's very complicated. For now, I'm going to be lazy and wait for someone to say "pretty please" before implementing it.

As I already stated in another PR, I don't think the plugin brings much value for anyone knowing both sbt and Github Actions, thus I removed it in a second commit + reworked the CI workflows.

### CODE REVIEW

**Comment by gaeljw** [comment]
@yanns and/or @avdv , if you've got a few minutes to check this, I would be thankful.

Otherwise, I don't mind merging myself, I'm quite confident with the changes ("famous last words :sweat_smile: ").

**Comment by yanns** [comment]
I'm in Black Friday stress and next week not available. I won't have time before the week after.

**Comment by gaeljw** [comment]
I'd like to merge this before merging Play 3 support and get both done by the beginning of next week ideally. But I don't want to "rush" anything. If you tell me you prefer to have a look before I merge this, I'll wait :)

**Comment by yanns** [comment]
For I let you decide here. If you feel safe, please go. If you feel you need a review, I'll give one, but only in 2 weeks.

**Review by avdv — APPROVED** [review]
Nice work :tada: !

**Comment by gaeljw** [comment]
@avdv Thanks for the review. I can't merge this one as it's expecting some checks that do not exist anymore (as I changed the CI).

Could you either give me some more rights so that I can change that myself, or at least change the rules to match the new name?

_(I created https://github.com/leanovate/play-mockws/pull/342 as I thought it was related to the fact that the PR contains two commits with different workflow definitions but it's not.)_

**Comment by avdv** [comment]
> Could you either give me some more rights so that I can change that myself, or at least change the rules to match the new name?

:ok_hand: I changed the branch protection rules to require the new workflow name.

**Pull request merged**
