### PR TITLE
scala 2.13.0-M5 support

### PR DESCRIPTION
**Pull request by yanns**

### CODE REVIEW

**Comment by yanns** [comment]
Needs new release of https://github.com/scoverage/sbt-scoverage/releases

**Comment by analytically** [comment]
Scoverage 1.6.0 was released

**Comment by avdv** [comment]
@yanns Hi, I am looking forward to the 2.13 support too, drop a line if you need a helping hand.

**Comment by yanns** [comment]
@avdv Thx for proposing!
I'm on holidays right now. If you want, you can open a new PR, and I'll close that one.
I'd actually prefer n pull requests:
- updating dependencies...
- before the PR to add support for scala 2.13 (with the minimal amount of changes)

**Comment by avdv** [comment]
> I'm on holidays right now. If you want, you can open a new PR, and I'll close that one.
> I'd actually prefer n pull requests:
> 
>     * updating dependencies...
> 
>     * before the PR to add support for scala 2.13 (with the minimal amount of changes)

Sure, can do. I'll look into it tomorrow.

**Comment by yanns** [comment]
Thx!

I just merged some PR to update dependencies. Be sure to fetch master.

**Comment by avdv** [comment]
New PRS: #63 and #64

**Pull request closed without merging**
