### PR TITLE
Use sbt-ci-release & setup release/publish workflow

### PR DESCRIPTION
**Pull request by gaeljw**
Aims to resolve https://github.com/leanovate/play-mockws/issues/328

---

I removed the usage of sbt-release in favour of sbt-ci-release which brings a simpler setup with default settings that should be okay for us. 
- sbt-ci-release eliminates the need for sbt-pgp and sbt-sonatype as well
- sbt-ci-release brings in sbt-dynver which dynamically sets a version from git tags and eliminates the need to maintain the version.sbt file

Then I used sbt-github-actions to generate the GH Workflows to handle publishing/releasing.

_To be noted that I'm not a big fan of the workflows it generates and would have preferred to set up the workflows myself in two distinct files for instance. Also I don't get why it generates download/inflate steps. But as it was already used, let's keep using it for now, at least you don't have to trust me for the workflows as they are generated :sweat_smile: _

---

Once this is merged, this means that to release the project we'll only have to push a tag named 'v...' to the repository.

Pushing/merging to master branch will also generates a publish for a SNAPSHOT version to Sonatype staging repository.

---

Also included in this PR but slightly unrelated: I explicitly set the scala version to be 2.13 rather than 2.12 (default), otherwise some tools (like IntelliJ) refuses to import the project.

---

Next steps:
- someone with admin rights need to enter the 4 secrets needed by the workflow in the project secrets:
  - `PGP_PASSPHRASE`: Can we reuse the one you used for last release @avdv ? Or I can generate a new one.
  - `PGP_SECRET`: same here
  - `SONATYPE_PASSWORD`: password part of the token to Sonatype. I guess you have one @avdv? Or you can generate a new one if you prefer to.
  - `SONATYPE_USERNAME`: username part of the token to Sonatype. same here.
- Merge this to master, check that a snapshot is published to Sonatype staging
- Optionally, create a tag v2.9.1 to check the release publishing

---

The sbt-ci-release [README](https://github.com/sbt/sbt-ci-release) should explain most of it if anything is unclear.

### CODE REVIEW

**Review by avdv — APPROVED** [review]

**Comment by avdv** [comment]
@gaeljw  Very nice! 

> Next steps:
> 
>     * someone with admin rights need to enter the 4 secrets needed by the workflow in the project secrets:
>       
>       * `PGP_PASSPHRASE`: Can we reuse the one you used for last release @avdv ? Or I can generate a new one.
>       * `PGP_SECRET`: same here
>       * `SONATYPE_PASSWORD`: password part of the token to Sonatype. I guess you have one @avdv? Or you can generate a new one if you prefer to.
>       * `SONATYPE_USERNAME`: username part of the token to Sonatype. same here.

Done. Note that the GPG key expires 2025-11-15. At that time.

>     * Merge this to master, check that a snapshot is published to Sonatype staging

Let's try :rocket:

**Comment by gaeljw** [comment]
Thanks @avdv 

https://github.com/leanovate/play-mockws/actions/runs/6935462004/job/18866268011

> published play-mockws_2.13 to https://oss.sonatype.org/content/repositories/snapshots/de/leanovate/play-mockws/play-mockws_2.13/2.9.0+15-25a0dafc-SNAPSHOT/play-mockws_2.13-2.9.0+15-25a0dafc-SNAPSHOT.pom
> ...
> published play-mockws_3 to https://oss.sonatype.org/content/repositories/snapshots/de/leanovate/play-mockws/play-mockws_3/2.9.0+15-25a0dafc-SNAPSHOT/play-mockws_3-2.9.0+15-25a0dafc-SNAPSHOT.pom

Look's like it worked! :confetti_ball:

**Comment by gaeljw** [comment]
I allowed myself to create a tag v2.9.1 to test a "real" release.

It [failed](https://github.com/leanovate/play-mockws/actions/runs/6940670010/job/18880036703) with:
> error [Sonatype] [MISSING_PROFILE] Profile de.leanovate.play-mockws is not found. Check your sonatypeProfileName setting in build.sbt

Sounds related to a setting I removed by mistake:
```scala
sonatypeProfileName := "de.leanovate"
```

I'll work on fixing this today.

**Comment by gaeljw** [comment]
After a few other fixes, it's now working fine for releases. We should see a 2.9.4 in Maven Central in a few hours.

**Pull request merged**
